version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
      include: scope
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      vue:
        patterns:
          - "vue"
          - "vue-*"
          - "@vue/*"
          - "primevue"
          - "@primevue/*"
      caido:
        patterns:
          - "@caido/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 3
    commit-message:
      prefix: ci
